jenkins:
  systemMessage: "jimangel.io demo: configured with JCasC plugin\n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"

jobs:
  - script: >
        pipelineJob("Seed or update all pipelines") {
            definition {
                cpsScm {
                       scm {
                            git{
                               remote {
                                       url("https://github.com/Tigerbeer123/jenkins-jobdsl-seedrepo-example.git")
                               }
                               branch("*/main")
                            }
                       }
                    }
                  }
               }

