jenkins:
  systemMessage: "Jenkins As Code Concept."
  views:
    - myView:
        name: "Jobs Config as Code"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"

jobs:
  - script: >
        pipelineJob("JobsConfigasCode") {
            definition {
                cpsScm {
                       scm {
                            git{
                               remote {
                                       url("https://github.com/Tigerbeer123/jenkins-jobdsl-seedrepo-example.git")
                               }
                               branch("*/main")
                            }
                       }
                    }
                  }
               }
